# Generated by Django 3.0.8 on 2021-07-26 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batchnum', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dosen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('kelompok', models.CharField(blank=True, choices=[('CYBERNETICS', 'CYBERNETICS'), ('EIS', 'EIS')], max_length=255, null=True)),
                ('peminatan', models.CharField(blank=True, choices=[('EDE', 'EDE'), ('EISD', 'EISD'), ('ERP', 'ERP'), ('SAG', 'SAG'), ('EIM', 'EIM')], max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keprof',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('keprof', models.CharField(blank=True, choices=[('DASPRO', 'DASPRO'), ('SISJAR', 'SISJAR'), ('SAG', 'SAG'), ('ERP', 'ERP'), ('EIM', 'EIM')], max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('rpb', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('probstat', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('basdat', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('dwbi', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('oop', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('apsi', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('alpro', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('web', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('ea', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('manlay', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('se', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('scm', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('akuntansi', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('manprosi', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('desjar', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('manjarkom', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('sisop', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
                ('ksi', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Peminatan',
            fields=[
                ('peminatancode', models.CharField(choices=[('EDE', 'EDE'), ('EISD', 'EISD'), ('ERP', 'ERP'), ('SAG', 'SAG'), ('EIM', 'EIM')], max_length=255, primary_key=True, serialize=False)),
                ('peminatanname', models.CharField(max_length=255)),
                ('kelompokkeahlian', models.CharField(blank=True, choices=[('CYBERNETICS', 'CYBERNETICS'), ('EIS', 'EIS')], max_length=255, null=True)),
                ('prasyarat1', models.CharField(blank=True, choices=[('RPB', 'RPB'), ('PROBSTAT', 'PROBSTAT'), ('BASDAT', 'BASDAT'), ('DWBI', 'DWBI'), ('OOP', 'OOP'), ('APSI', 'APSI'), ('ALPRO', 'ALPRO'), ('WEB', 'WEB'), ('EA', 'EA'), ('MANLAY', 'MANLAY'), ('SE', 'SE'), ('SCM', 'SCM'), ('AKUNTANSI', 'AKUNTANSI'), ('MANPROSI', 'MANPROSI'), ('DESJAR', 'DESJAR'), ('MANJARKOM', 'MANJARKOM'), ('SISOP', 'SISOP'), ('KSI', 'KSI')], max_length=255, null=True)),
                ('prasyarat2', models.CharField(blank=True, choices=[('RPB', 'RPB'), ('PROBSTAT', 'PROBSTAT'), ('BASDAT', 'BASDAT'), ('DWBI', 'DWBI'), ('OOP', 'OOP'), ('APSI', 'APSI'), ('ALPRO', 'ALPRO'), ('WEB', 'WEB'), ('EA', 'EA'), ('MANLAY', 'MANLAY'), ('SE', 'SE'), ('SCM', 'SCM'), ('AKUNTANSI', 'AKUNTANSI'), ('MANPROSI', 'MANPROSI'), ('DESJAR', 'DESJAR'), ('MANJARKOM', 'MANJARKOM'), ('SISOP', 'SISOP'), ('KSI', 'KSI')], max_length=255, null=True)),
                ('prasyarat3', models.CharField(blank=True, choices=[('RPB', 'RPB'), ('PROBSTAT', 'PROBSTAT'), ('BASDAT', 'BASDAT'), ('DWBI', 'DWBI'), ('OOP', 'OOP'), ('APSI', 'APSI'), ('ALPRO', 'ALPRO'), ('WEB', 'WEB'), ('EA', 'EA'), ('MANLAY', 'MANLAY'), ('SE', 'SE'), ('SCM', 'SCM'), ('AKUNTANSI', 'AKUNTANSI'), ('MANPROSI', 'MANPROSI'), ('DESJAR', 'DESJAR'), ('MANJARKOM', 'MANJARKOM'), ('SISOP', 'SISOP'), ('KSI', 'KSI')], max_length=255, null=True)),
                ('prasyarat4', models.CharField(blank=True, choices=[('RPB', 'RPB'), ('PROBSTAT', 'PROBSTAT'), ('BASDAT', 'BASDAT'), ('DWBI', 'DWBI'), ('OOP', 'OOP'), ('APSI', 'APSI'), ('ALPRO', 'ALPRO'), ('WEB', 'WEB'), ('EA', 'EA'), ('MANLAY', 'MANLAY'), ('SE', 'SE'), ('SCM', 'SCM'), ('AKUNTANSI', 'AKUNTANSI'), ('MANPROSI', 'MANPROSI'), ('DESJAR', 'DESJAR'), ('MANJARKOM', 'MANJARKOM'), ('SISOP', 'SISOP'), ('KSI', 'KSI')], max_length=255, null=True)),
                ('kuota', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberid', models.CharField(max_length=255, null=True)),
                ('username', models.CharField(max_length=255)),
                ('role', models.CharField(choices=[('MAHASISWA', 'MAHASISWA'), ('DOSEN', 'DOSEN'), ('DOSEN PEMBINA', 'DOSEN PEMBINA'), ('ADMIN', 'ADMIN')], max_length=255, null=True)),
                ('fullname', models.CharField(max_length=255, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('schoolyear', models.IntegerField(blank=True, null=True)),
                ('studentclass', models.CharField(blank=True, max_length=255, null=True)),
                ('lecturerguardian', models.CharField(blank=True, max_length=255, null=True)),
                ('studyprogram', models.CharField(blank=True, max_length=255, null=True)),
                ('faculty', models.CharField(blank=True, max_length=255, null=True)),
                ('peminatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_peminatan', to='pipeapp.Peminatan')),
            ],
        ),
        migrations.CreateModel(
            name='StatusServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('isAvailable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TukarPeminatan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pengajuan I', 'Pengajuan I'), ('Pengajuan II', 'Pengajuan II'), ('Disetujui', 'Disetujui'), ('Ditolak I', 'Ditolak I'), ('Ditolak II', 'Ditolak II')], max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mahasiswa1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswasatu', to='pipeapp.Profile')),
                ('mahasiswa2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mahasiswadua', to='pipeapp.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Seleksi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score1', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('score2', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('batch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batchnumber', to='pipeapp.Batch')),
                ('pilihan1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihansatu', to='pipeapp.Peminatan')),
                ('pilihan2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pilihandua', to='pipeapp.Peminatan')),
                ('result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pipeapp.Peminatan')),
                ('studentid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seleksi_student', to='pipeapp.Profile')),
            ],
        ),
    ]
