# Generated by Django 3.0.8 on 2021-07-26 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='akuntansi',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='alpro',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='apsi',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='basdat',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='desjar',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='dwbi',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='ea',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='ksi',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='manjarkom',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='manlay',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='manprosi',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='oop',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='probstat',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='rpb',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='scm',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='se',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='sisop',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='web',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, null=True),
        ),
        migrations.AlterField(
            model_name='peminatan',
            name='kelompokkeahlian',
            field=models.CharField(blank=True, choices=[('CYBERNETICS', 'CYBERNETICS'), ('EIS', 'EIS')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='seleksi',
            name='score1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='seleksi',
            name='score2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
