# Generated by Django 3.2.5 on 2021-08-01 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeapp', '0002_auto_20210801_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleksi',
            name='score1',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='seleksi',
            name='score2',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
        ),
    ]
