# Generated by Django 3.2.5 on 2021-08-01 05:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeapp', '0005_auto_20210801_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seleksi',
            name='score1',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='seleksi',
            name='score2',
            field=models.DecimalField(decimal_places=1, default=Decimal('0'), max_digits=3, null=True),
        ),
    ]
