# Generated by Django 3.2.5 on 2021-08-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeapp', '0008_alter_seleksi_result'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bobot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kordas', models.IntegerField(blank=True, default=0, null=True)),
                ('aslab', models.IntegerField(blank=True, default=0, null=True)),
                ('anggota', models.IntegerField(blank=True, default=0, null=True)),
                ('pilihan1', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('MAHASISWA', 'MAHASISWA'), ('DOSEN PEMBINA', 'DOSEN PEMBINA'), ('ADMIN', 'ADMIN')], max_length=255, null=True),
        ),
    ]
