# Generated by Django 3.2.5 on 2021-08-13 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeapp', '0010_peminatan_sisakuota'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bobot',
            old_name='aslab',
            new_name='asisten',
        ),
        migrations.RemoveField(
            model_name='peminatan',
            name='sisakuota',
        ),
        migrations.AddField(
            model_name='keprof',
            name='kategori',
            field=models.CharField(blank=True, choices=[('KORDAS', 'KORDAS'), ('ASISTEN', 'ASISTEN'), ('ANGGOTA', 'ANGGOTA')], max_length=255),
        ),
    ]
