# Generated by Django 3.2.5 on 2021-08-22 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeapp', '0011_auto_20210813_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='peminatan',
            name='sisakuota',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
