# Generated by Django 3.2.5 on 2021-09-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeapp', '0012_peminatan_sisakuota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keprof',
            name='keprof',
            field=models.CharField(blank=True, choices=[('EDE', 'EDE'), ('EIM', 'EIM'), ('SAG', 'SAG'), ('ESS', 'ESS'), ('EISD', 'EISD')], max_length=255),
        ),
    ]
